# Generated by Django 3.1.1 on 2024-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expectedGraduationYear',
            field=models.IntegerField(default=2024),
        ),
    ]
