# Generated by Django 3.1.1 on 2024-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240329_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expectedGraduationYear',
            field=models.IntegerField(blank=True, default=2024, verbose_name='Expected'),
        ),
    ]
