# Generated by Django 3.1.1 on 2024-03-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240329_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expectedGraduationYear',
            field=models.IntegerField(default=2024, verbose_name='First'),
        ),
    ]
