# Generated by Django 3.1.1 on 2024-03-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240329_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expectedGraduationTerm',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], default='FALL', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='expectedGraduationYear',
            field=models.IntegerField(default=2024),
        ),
    ]
