# Generated by Django 3.1.1 on 2024-03-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240329_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expectedGraduationTerm',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='FALL', max_length=6),
        ),
    ]
