# Generated by Django 3.1.1 on 2024-03-29 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240329_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Course Code')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('credits', models.IntegerField(verbose_name='Credits')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('P', 'Pass'), ('W', 'Withdraw'), ('CR', 'Credit'), ('I', 'Incomplete'), ('WF', 'Withdraw Fail'), ('WP', 'Withdraw Pass')], max_length=2, verbose_name='Grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
