# Generated by Django 3.1.1 on 2024-04-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(null=True, upload_to='excel_files/'),
        ),
    ]
