# Generated by Django 3.1.1 on 2024-04-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expectedGraduationTerm',
            field=models.CharField(blank=True, choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='expectedGraduationYear',
            field=models.CharField(blank=True, choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], max_length=4),
        ),
    ]
