# Generated by Django 3.1.1 on 2024-04-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20240404_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='name',
        ),
    ]
