# Generated by Django 3.1.1 on 2024-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20240407_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('credits', models.PositiveIntegerField()),
                ('corequisites', models.ManyToManyField(blank=True, related_name='coreqs', to='users.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='expectedGraduationTerm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expectedGraduationYear',
        ),
        migrations.AddField(
            model_name='user',
            name='expected_grad_term',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_grad_year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, help_text='Upload your completed excel template. You may download a template on the home page.', null=True, upload_to='excel_files/'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('program_type', models.CharField(choices=[('MAJ', 'Major'), ('MIN', 'Minor'), ('CERT', 'Certificate'), ('TRCK', 'Interest Track')], default='MAJ', max_length=4)),
                ('required_courses', models.ManyToManyField(to='users.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='offered',
            field=models.ManyToManyField(to='users.CourseTerm'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prereqs', to='users.Course'),
        ),
    ]
