# Generated by Django 3.1.1 on 2024-05-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20240508_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseterm',
            name='name',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expected_grad_term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=6, null=True),
        ),
    ]
